add `cg::foo` include test, I broke CMakeLists.txt, 0.0.3
```
(main) Ryans-MacBook-Air:cudagrad ryan$ py
Python 3.11.1 (main, Apr 19 2023, 18:41:42) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cudagrad
>>> cudagrad.foo
<built-in method foo of PyCapsule object at 0x10299fc30>
>>> cudagrad.foo()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: foo(): incompatible function arguments. The following argument types are supported:
    1. (arg0: int) -> int

Invoked with:
>>> cudagrad.foo(1)
2
```