PyPI 0.1.0 working CUDA `hello` (#35)
* Tentatively working `hello`:

```
[ 33%] Building NVCC (Device) object CMakeFiles/tensor.dir/src/tensor_generated_operations.cu.o
[ 66%] Building CXX object CMakeFiles/tensor.dir/src/bindings.cpp.o
[100%] Linking CXX shared library tensor.so
[100%] Built target tensor
ryan@Lambda-TensorBook:~/cudagrad$ cd build/
ryan@Lambda-TensorBook:~/cudagrad/build$ ls
CMakeCache.txt  CMakeFiles  cmake_install.cmake  Makefile  pybind11  tensor.so
ryan@Lambda-TensorBook:~/cudagrad/build$ python
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tenosr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tenosr'
>>> import tensor
>>> tensor
<module 'tensor' from '/home/ryan/cudagrad/build/tensor.so'>
>>> tensor.hello
<built-in method hello of PyCapsule object at 0x7fb503eaad90>
>>> tensor.hello()
Hello, GPU!

```

* Add copy tensor.so to cudagrad during install step

* Simplify setup.py, tentatively working pip install .

* Copy `tensor.so` from lib to cudagrad folder:

```
ryan@Lambda-TensorBook:~/cudagrad$ pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /home/ryan/cudagrad
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: cudagrad
  Building wheel for cudagrad (pyproject.toml) ... done
  Created wheel for cudagrad: filename=cudagrad-0.1.0-cp310-cp310-linux_x86_64.whl size=1460062 sha256=a9da539885df2e580218a83c12fe01d25030e6e9681fc24a1ce59079bf3821ac
  Stored in directory: /tmp/pip-ephem-wheel-cache-pzk9tev8/wheels/6e/97/c6/cc52a8580426cb31cc0243410052955dcf33c64ff395da9f71
Successfully built cudagrad
Installing collected packages: cudagrad
  Attempting uninstall: cudagrad
    Found existing installation: cudagrad 0.1.0
    Uninstalling cudagrad-0.1.0:
      Successfully uninstalled cudagrad-0.1.0
Successfully installed cudagrad-0.1.0
ryan@Lambda-TensorBook:~/cudagrad$ cd build/
ryan@Lambda-TensorBook:~/cudagrad/build$ ls
bdist.linux-x86_64  lib.linux-x86_64-3.10  temp.linux-x86_64-3.10
ryan@Lambda-TensorBook:~/cudagrad/build$ cd temp.linux-x86_64-3.10/
ryan@Lambda-TensorBook:~/cudagrad/build/temp.linux-x86_64-3.10$ ls
CMakeCache.txt  CMakeFiles  cmake_install.cmake  Makefile  pybind11
ryan@Lambda-TensorBook:~/cudagrad/build/temp.linux-x86_64-3.10$ cd ..
ryan@Lambda-TensorBook:~/cudagrad/build$ cd lib.linux-x86_64-3.10/
ryan@Lambda-TensorBook:~/cudagrad/build/lib.linux-x86_64-3.10$ ls
cudagrad  tensor.so
ryan@Lambda-TensorBook:~/cudagrad/build/lib.linux-x86_64-3.10$ cd cudagrad/
ryan@Lambda-TensorBook:~/cudagrad/build/lib.linux-x86_64-3.10/cudagrad$ ls
__init__.py  linear.py  mlp.py  moons.py  nn.py  tensor.so
```
```
ryan@Lambda-TensorBook:/$ python
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cudagrad
>>> cudagrad.tensor.hello()
Hello, GPU!
>>> cudagrad
<module 'cudagrad' from '/home/ryan/.local/lib/python3.10/site-packages/cudagrad/__init__.py'>
>>> exit()
ryan@Lambda-TensorBook:/$ cd /home/ryan/.local/lib/python3.10/site-packages/cudagrad/
ryan@Lambda-TensorBook:~/.local/lib/python3.10/site-packages/cudagrad$ ls
__init__.py  linear.py  mlp.py  moons.py  nn.py  __pycache__  tensor.so
```

* Stop ignoring CMakeLists.txt

* TEMP fix to fix project.py test multi-CMakeLists problem

* Fix test removing CMakeLists TEMP