add pip compile speed test to makefile.py (~6 seconds currently):
```
(main) Ryans-MacBook-Air:cudagrad ryan$ python makefile.py DB pip_speed
Installation succeeded!
Elapsed time: 6.813880205154419 seconds
(main) Ryans-MacBook-Air:cudagrad ryan$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   makefile.py
	modified:   performance.db

no changes added to commit (use "git add" and/or "git commit -a")
(main) Ryans-MacBook-Air:cudagrad ryan$ sqlite3 performance.db
SQLite version 3.39.5 2022-10-14 20:58:05
Enter ".help" for usage hints.
sqlite> .tables
pip_compile_speed  result             test
sqlite> select * from pip_compile_speed
   ...> ;
1|6.81388020515442|2023-08-21 16:27:51
sqlite> .mode columsn
Error: mode should be one of: ascii box column csv html insert json line list markdown qbox quote table tabs tcl
sqlite> .mode columns
sqlite> .headers on
sqlite> select * from pip_compile_speed;
id  seconds           created_at
--  ----------------  -------------------
1   6.81388020515442  2023-08-21 16:27:51
sqlite> .q
(main) Ryans-MacBook-Air:cudagrad ryan$ sqlite3 performance.db
SQLite version 3.39.5 2022-10-14 20:58:05
Enter ".help" for usage hints.
sqlite> .q
(main) Ryans-MacBook-Air:cudagrad ryan$ python makefile.py DB pip_speed
Installation succeeded!
Elapsed time: 6.552322149276733 seconds
(main) Ryans-MacBook-Air:cudagrad ryan$ sqlite3 performance.db
SQLite version 3.39.5 2022-10-14 20:58:05
Enter ".help" for usage hints.
sqlite> .headers on
sqlite> .mode column
sqlite> select * from pip_speed_test;
Parse error: no such table: pip_speed_test
sqlite> .tables
pip_compile_speed  result             test
sqlite> select * from pip_compile_speed;
id  seconds           created_at
--  ----------------  -------------------
1   6.81388020515442  2023-08-21 16:27:51
2   6.55232214927673  2023-08-21 16:28:27
sqlite> .q
```