fixes #34 add MANFIFEST.in (include src/cudagrad.hpp) 0.0.11 pip install works:
```
Ryans-MacBook-Air:~ ryan$ cd junk
Ryans-MacBook-Air:junk ryan$ pip install cudagrad
Collecting cudagrad
  Downloading cudagrad-0.0.10.tar.gz (4.8 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: micrograd in /Users/ryan/.pyenv/versions/3.11.1/lib/python3.11/site-packages (from cudagrad) (0.1.0)
Building wheels for collected packages: cudagrad
  Building wheel for cudagrad (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for cudagrad (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [45 lines of output]
      /private/var/folders/8f/pmq_g1556d942470cc0ghx480000gn/T/pip-build-env-312xpbhf/overlay/lib/python3.11/site-packages/setuptools/config/_apply_pyprojecttoml.py:62: _WouldIgnoreField: `optional-dependencies` defined outside of `pyproject.toml` would be ignored.
      !!

              ********************************************************************************
              ##########################################################################
              # configuration would be ignored/result in error due to `pyproject.toml` #
              ##########################################################################

              The following seems to be defined outside of `pyproject.toml`:

              `optional-dependencies = {'test': 'pytest'}`

              According to the spec (see the link below), however, setuptools CANNOT
              consider this value unless `optional-dependencies` is listed as `dynamic`.

              https://packaging.python.org/en/latest/specifications/declaring-project-metadata/

              For the time being, `setuptools` will still consider the given value (as a
              **transitional** measure), but please note that future releases of setuptools will
              follow strictly the standard.

              To prevent this warning, you can list `optional-dependencies` under `dynamic` or alternatively
              remove the `[project]` table from your file and rely entirely on other means of
              configuration.

              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
              ********************************************************************************

      !!
        _handle_missing_dynamic(dist, project_table)
      running bdist_wheel
      running build
      running build_ext
      clang -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Users/ryan/.pyenv/versions/3.11.1/include/python3.11 -c flagcheck.cpp -o flagcheck.o -std=c++17
      building 'cudagrad' extension
      creating build
      creating build/temp.macosx-13.2-arm64-cpython-311
      creating build/temp.macosx-13.2-arm64-cpython-311/src
      clang -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -DVERSION_INFO=0.0.10 -I/private/var/folders/8f/pmq_g1556d942470cc0ghx480000gn/T/pip-build-env-312xpbhf/overlay/lib/python3.11/site-packages/pybind11/include -I/Users/ryan/.pyenv/versions/3.11.1/include/python3.11 -c src/main.cpp -o build/temp.macosx-13.2-arm64-cpython-311/src/main.o -std=c++17 -mmacosx-version-min=10.14 -fvisibility=hidden -g0
      src/main.cpp:1:10: fatal error: 'cudagrad.hpp' file not found
      #include "cudagrad.hpp"
               ^~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cudagrad
Failed to build cudagrad
ERROR: Could not build wheels for cudagrad, which is required to install pyproject.toml-based projects
Ryans-MacBook-Air:junk ryan$ pip cache purge
Files removed: 9
Ryans-MacBook-Air:junk ryan$ pip install cudagrad
Collecting cudagrad
  Downloading cudagrad-0.0.11.tar.gz (9.2 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: micrograd in /Users/ryan/.pyenv/versions/3.11.1/lib/python3.11/site-packages (from cudagrad) (0.1.0)
Building wheels for collected packages: cudagrad
  Building wheel for cudagrad (pyproject.toml) ... done
  Created wheel for cudagrad: filename=cudagrad-0.0.11-cp311-cp311-macosx_13_0_arm64.whl size=102081 sha256=1e2f1659dc57a059364a7d952440821a805e52b56894cb1304ea4add70899c64
  Stored in directory: /Users/ryan/Library/Caches/pip/wheels/29/14/00/991498fe50455dd2fc7f403ced5832f545e5543fd1b0d99660
Successfully built cudagrad
Installing collected packages: cudagrad
Successfully installed cudagrad-0.0.11
Ryans-MacBook-Air:junk ryan$ py
Python 3.11.1 (main, Apr 19 2023, 18:41:42) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cudagrad
>>> cudagrad.tensor([1],[2]).data
[2.0]
>>>
```